name: Update Catalyst Proposal Data

on:
  schedule:
    - cron: '10 0 * * 1'  # Runs at 00:10 UTC every Monday
    - cron: '10 0 * * 3'  # Runs at 00:10 UTC every Wednesday
    - cron: '10 0 * * 5'  # Runs at 00:10 UTC every Friday
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

permissions:
  contents: write
  # More explicit permissions:
  issues: read
  pull-requests: read

jobs:
  update-catalyst-data:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      NEXT_PUBLIC_MILESTONES_URL: 'https://milestones.projectcatalyst.io'
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PROJECT_IDS: ${{ secrets.PROJECT_IDS }}
      LIDO_CSRF_TOKEN: ${{ secrets.LIDO_CSRF_TOKEN }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        working-directory: scripts/sidan-gov
        
      - name: Update Catalyst Data
        run: |
          cd scripts/sidan-gov
          npm run update-catalyst-docs
        
      - name: Debug file locations
        run: |
          echo "Current working directory: $(pwd)"
          echo "Repository contents:"
          ls -la
          echo "Checking for catalyst files:"
          find . -name "*.json" -path "*/catalyst*" 2>/dev/null || echo "No catalyst JSON files found"
          echo "Checking sidan-gov-updates directory:"
          ls -la sidan-gov-updates/ 2>/dev/null || echo "sidan-gov-updates directory not found"
          echo "Checking sidan-gov-updates/catalyst-proposals directory:"
          ls -la sidan-gov-updates/catalyst-proposals/ 2>/dev/null || echo "catalyst-proposals directory not found"
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          # Check if the catalyst data file exists
          if [ -f "sidan-gov-updates/catalyst-proposals/catalyst-data.json" ]; then
            echo "Found catalyst-data.json, adding to git..."
            git add sidan-gov-updates/catalyst-proposals/catalyst-data.json
            git status
            git diff --cached --name-only
            if git diff --cached --quiet; then
              echo "No changes to commit"
            else
              echo "Committing changes..."
              git commit -m "Update Catalyst Proposal Data"
              git push
              echo "Changes committed and pushed successfully"
            fi
          else
            echo "catalyst-data.json not found at expected location"
            echo "Available files in sidan-gov-updates:"
            find sidan-gov-updates -type f 2>/dev/null || echo "No files found in sidan-gov-updates"
          fi 