name: Update Discord Stats
on:
  schedule:
    - cron: '0 2 1 * *' # 1st day of the month at 2:00 AM UTC
  workflow_dispatch:

permissions:
  contents: write      # allow GITHUB_TOKEN to push

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read config and set expected repository
        id: config
        run: |
          CONFIG=$(cat org-stats-config.json)
          ORG_NAME=$(echo "$CONFIG" | jq -r '.organization.name')
          GOV_REPO=$(echo "$CONFIG" | jq -r '.repositories.governance')
          EXPECTED_REPO="$ORG_NAME/$GOV_REPO"
          echo "expected_repo=$EXPECTED_REPO" >> $GITHUB_OUTPUT
          echo "Current repository: ${{ github.repository }}"
          echo "Expected repository: $EXPECTED_REPO"
      
      - name: Check repository
        if: github.repository != steps.config.outputs.expected_repo
        run: |
          echo "This workflow is designed to run only in ${{ steps.config.outputs.expected_repo }}"
          echo "Current repository: ${{ github.repository }}"
          exit 1

      - name: Run Discord-Stats Action
        uses: Signius/discord-stats-action@1.0.2
        with:
          discord-token: ${{ secrets.DISCORD_TOKEN }}
          guild-id:       ${{ secrets.GUILD_ID }}
          output-file:    sidan-gov-updates/discord-stats/stats.json
          backfill:       'false'
          backfill-year:  '2025'

      - name: Commit stats.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sidan-gov-updates/discord-stats/stats.json
          git commit -m "chore: monthly Discord stats" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
